# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %> || eaa70831b0514fbd39420de71f52ecc4a8fdeab8641169e41571b2ddd835323328b0e2a83186ebd03bebc890e54993b550c8eb2c687669f5c74a901e08328b33

test:
  secret_key_base: a8a0a4e3341bbaef9db3dc9db04eebdafd87a99df1cf3a2afb4ce60a0f26f90dac878d5c73de7783c46b1eec7dd4fc9cae8aded3e8978288a24875a7a13baf3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
